version: "3.9"

services:
  muntree-backend:
    build: .
    container_name: muntree-backend
    env_file: .env
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000